### ISSUE TITLE
[GR-59701] 23.0.1 breaks ///usr/bin/env java --source 21 "$0" "$@"; exit $? causes "error: exporting a package from system module java.base is not allowed with —release"

### ISSUE THREAD

**Issue by HolgerMassmann** [oracle/graal#10014]
**Describe the issue**
///usr/bin/env java --source 21 "$0" "$@"; exit $? causes "error: exporting a package from system module java.base is not allowed with —release"

**Steps to reproduce the issue**
SDKMAN installed 23.0.1-graal on MacOS M1 
```
///usr/bin/env java --source 21 "$0" "$@"; exit $?

import java.time.ZoneId;
import java.time.ZonedDateTime;

public class Utc2 {

   public static void main( String[] args ) {
    System.out.printf( "Epoch seconds: %1$d%n", ZonedDateTime.now().toEpochSecond() );
  }
}
```

```
$ sw_vers
ProductName:		macOS
ProductVersion:		15.0.1
BuildVersion:		24A348
```

**More details**
Save the script above as Utc2, chmod 755 Utc2 and executing ./Utc2 the following error message printed:
```
error: exporting a package from system module java.base is not allowed with --release
1 error
error: compilation failed
```

This works with 22.0.1-graal or 23-open.

**Comment by HolgerMassmann** [comment]
Probably does not work with 23-graal, but not tested

**Comment by HolgerMassmann** [comment]
Hit wrong button

**Comment by oubidar-Abderrahim** [comment]
This should be fixed by https://github.com/oracle/graal/commit/1767a1191ea070fe58bf54c99e3b2eff3ac71950 and will be backported to 23.0.2 for next January's CPU release
