### PR TITLE
[GR-43233] Remove isMIME decodeBlock parameter workaround for JDK 17 or below

### LINKED ISSUE #5686: [GR-43233] Native image fails to build with JDK 17.0.6+
Native image fails to build with the latest JDK 17 development branch. It throws:

```
java.lang.NoSuchMethodError: java.util.Base64$Decoder.decodeBlock([BII[BIZ)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.graphbuilderconf.InvocationPlugins$Checks.checkResolvable(InvocationPlugins.java:1056)
```

This is caused by [this JDK17 backport](https://github.com/openjdk/jdk17u-dev/commit/07050b000ce20350c55505fbc5595c0b6c3052b5). SVM assumes that if running below Java 18, there's no `isMIME` parameter. E.g.: 

```java
    public static final HotSpotForeignCallDescriptor BASE64_DECODE_BLOCK = JavaVersionUtil.JAVA_SPEC < 18
                    ? new HotSpotForeignCallDescriptor(LEAF, NOT_REEXECUTABLE, any(), "base64DecodeBlock", int.class, Word.class,
                                    int.class, int.class, Word.class, int.class, boolean.class)
                    : new HotSpotForeignCallDescriptor(LEAF, NOT_REEXECUTABLE, any(), "base64DecodeBlock", int.class, Word.class,
                                    int.class, int.class, Word.class, int.class, boolean.class, boolean.class);

```

However, once the backport was added, this check should no longer be necessary.

The backport is part of JDK 17.0.6+.

### PR DESCRIPTION
**Pull request by galderz**
Fixed #5686

### CODE REVIEW

**Comment by fniephaus** [comment]
Thanks for the fix, @galderz. Could you please remove the unneeded import and squash the commits into one?

**Comment by galderz** [comment]
Fixed the import and amended commit.

**Comment by galderz** [comment]
Another style issue, incoming fix...

**Comment by fniephaus** [comment]
We may need a different fix for this. We're discussing this internally. Will let you know when I know more...

**Comment by fniephaus** [comment]
Closing this in favor of https://github.com/oracle/graal/pull/5695.
