### ISSUE TITLE
 substratevm doesn't build with mx on graalvm-0.30.2 on linux

### ISSUE THREAD

**Issue by cboddy** [oracle/graal#285]
Hello, excited to try substratevm, is there a tag of this repo (and/or mx) that can be used to build with the graalvm available on the oracle website (or another vm)? Currently the oracle-site http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html has version 0.30.2 available, which produces the following error the head (e151047) of mx

```
home/chrirs/software/graal/truffle/src/com.oracle.truffle.api.vm/src/c
om/oracle/truffle/api/vm/PolyglotImpl.java:169: error: method does not 
override or implement a method from a supertype
    @Override
    ^
/home/chrirs/software/graal/truffle/src/com.oracle.truffle.api.vm/src/c
om/oracle/truffle/api/vm/PolyglotImpl.java:186: error: method does not 
override or implement a method from a supertype
    @Override
    ^
/home/chrirs/software/graal/truffle/src/com.oracle.truffle.api.vm/src/c
om/oracle/truffle/api/vm/PolyglotContextImpl.java:269: error: method do
es not override or implement a method from a supertype
    @Override
    ^
/home/chrirs/software/graal/truffle/src/com.oracle.truffle.api.vm/src/c
om/oracle/truffle/api/vm/PolyglotContextImpl.java:277: error: method do
es not override or implement a method from a supertype
    @Override
    ^
/home/chrirs/software/graal/truffle/src/com.oracle.truffle.api.vm/src/c
om/oracle/truffle/api/vm/PolyglotValue.java:861: error: method does not
 override or implement a method from a supertype
        @Override
        ^
/home/chrirs/software/graal/truffle/src/com.oracle.truffle.api.vm/src/c
om/oracle/truffle/api/vm/PolyglotValue.java:866: error: method does not
 override or implement a method from a supertype
        @Override
        ^
/home/chrirs/software/graal/truffle/src/com.oracle.truffle.api.vm/src/c
om/oracle/truffle/api/vm/PolyglotValue.java:876: error: method does not
 override or implement a method from a supertype
7 errors

Compiling com.oracle.truffle.api.vm with javac-daemon failed
1 build tasks failed
```

Very pleased substrate-vm was open-sourced!

**Comment by dougxc** [comment]
Hi @cboddy , you cannot use GraalVM to develop with this repo precisely due to the incompatibilities you are seeing. This is like trying to use a standard JDK to extend the API a core Java class (e.g. `java.lang.String`). You need to start doing all kinds of class path trickery to make it work. So for now, I recommend just using the JVMCI JDK8 binaries available at http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html or https://github.com/dougxc/openjdk8-jvmci-builder/releases.

**Comment by dougxc** [comment]
@cboddy , please re-open this issue if you have further comments.

**Comment by cboddy** [comment]
@dougxc thanks for the swift reply,  will try that. Thanks for closing the issue.
