### ISSUE TITLE
ClassNotFound:  com.sun.xml.internal.bind.v2.ContextFactory

### ISSUE THREAD

**Issue by crowlogic** [oracle/graal#2132]
How do I get native-image to respect the jaxb contextFactory property? 

Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at util.AutoHashMap.getOrCreate(AutoHashMap.java:56)
	at com.crowlogic.b2tf.Configuration.loadConfiguation(Configuration.java:1359)
	at com.crowlogic.b2tf.Calibrator.main(Calibrator.java:87)
Caused by: java.lang.RuntimeException: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at com.crowlogic.b2tf.Configuration.loadFromXML(Configuration.java:1746)
	at com.crowlogic.b2tf.Configuration.readConfigurationFromXML(Configuration.java:1364)
	at com.crowlogic.b2tf.Configuration.lambda$0(Configuration.java:1354)
	at util.AutoHashMap.newValueInstance(AutoHashMap.java:72)
	at util.AutoHashMap.getOrCreate(AutoHashMap.java:42)
	... 2 more
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:278)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:421)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
	at com.crowlogic.b2tf.Configuration.loadFromXML(Configuration.java:1730)
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.ClassLoader.loadClass(Target_java_lang_ClassLoader.java:160)
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122)
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:276)
	... 10 more

here is my maven snippet
		<plugin>
				<groupId>org.graalvm.nativeimage</groupId>
				<artifactId>native-image-maven-plugin</artifactId>
				<version>19.3.1</version>
				<executions>
					<execution>
						<goals>
							<goal>native-image</goal>
						</goals>
						<phase>package</phase>
					</execution>
				</executions>
				<configuration>
					<skip>false</skip>
					<imageName>calibrator</imageName>
					<buildArgs>
						-H:ReflectionConfigurationFiles=../reflect.json
						-H:IncludeResourceBundles=javax.xml.bind.Messages
						-H:-UseServiceLoaderFeature --no-fallback
						--report-unsupported-elements-at-runtime
						-H:IncludeResourceBundles=gnu/getopt/MessagesBundle
						-H:+TraceClassInitialization
						--initialize-at-build-time=util.AutoHashMap
						--initialize-at-build-time=com.crowlogic.b2tf.Calibrator$Datasource
						--initialize-at-build-time=com.crowlogic.b2tf.Calibrator
						--initialize-at-build-time=com.crowlogic.b2tf.ConsoleProgram
						--initialize-at-build-time=com.crowlogic.b2tf.data.model.Side
						--initialize-at-build-time=com.crowlogic.b2tf.TradeType
						--initialize-at-build-time=com.sun.xml.internal.bind.v2.ContextFactory
					</buildArgs>
					<mainClass>com.crowlogic.b2tf.Calibrator</mainClass>
				</configuration>

**Comment by crowlogic** [comment]
I hacked around this by creating my own implementation

package com.sun.xml.internal.bind.v2;

public class ContextFactory extends
                            com.sun.xml.bind.v2.ContextFactory
{

}

**Comment by fernando-valdez** [comment]
Hi @crowlogic, would you kindly share your reflect.json file?

**Comment by crowlogic** [comment]
[reflect-config.json.txt](https://github.com/oracle/graal/files/4201028/reflect-config.json.txt)

if I include the file that is actually the type I'm trying to access i get a different compile-time error described at https://github.com/oracle/graal/issues/2135

Thank you for your help

**Comment by jramirez-isc** [comment]
@crowlogic Seems like you are using the fix provided here: https://github.com/oracle/graal/issues/379. That fix is still working in 19.3.1 under the assumptions described there. Can you please provide a reproducer of this issue? 

Also, make sure you have the right dependencies in your `pom.xml`, this is part of the build.gradle from the still working example:
```
dependencies {
	compile group: 'com.sun.xml.bind', name: 'jaxb-impl', version: '2.3.2'
	compile group: 'com.sun.xml.bind', name: 'jaxb-core', version: '2.3.0.1'
}
```

**Comment by crowlogic** [comment]
@jramirez-isc  the only jaxb import I have is 

		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.0</version>
		</dependency>

**Comment by crowlogic** [comment]
@jramirez-isc I changed the imports to get the ones you specified, and it seems to work.. gets further anyway, I had to add ReflectionNavigator to the reflect.json file

Now, I'm getting a different message..progress, i think?

Exception in thread "main" java.lang.NoSuchMethodError: javax.xml.bind.annotation.XmlType.factoryClass()
	at com.sun.xml.bind.v2.model.annotation.RuntimeInlineAnnotationReader.getClassValue(RuntimeInlineAnnotationReader.java:145)
	at com.sun.xml.bind.v2.model.annotation.RuntimeInlineAnnotationReader.getClassValue(RuntimeInlineAnnotationReader.java:57)
	at com.sun.xml.bind.v2.model.impl.ClassInfoImpl.hasFactoryConstructor(ClassInfoImpl.java:1299)
	at com.sun.xml.bind.v2.model.impl.ClassInfoImpl.<init>(ClassInfoImpl.java:208)
	at com.sun.xml.bind.v2.model.impl.RuntimeClassInfoImpl.<init>(RuntimeClassInfoImpl.java:102)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createClassInfo(RuntimeModelBuilder.java:113)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createClassInfo(RuntimeModelBuilder.java:84)
	at com.sun.xml.bind.v2.model.impl.ModelBuilder.getClassInfo(ModelBuilder.java:257)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:103)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:84)
	at com.sun.xml.bind.v2.model.impl.ModelBuilder.getClassInfo(ModelBuilder.java:227)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:98)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:84)
	at com.sun.xml.bind.v2.model.impl.ModelBuilder.getTypeInfo(ModelBuilder.java:375)
	at com.sun.xml.bind.v2.model.impl.ModelBuilder.getTypeInfo(ModelBuilder.java:390)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:465)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:303)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:139)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1156)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:165)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:297)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:286)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:391)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
	at com.crowlogic.b2tf.Configuration.loadFromXML(Configuration.java:1721)
	at com.crowlogic.b2tf.Configuration.readConfigurationFromXML(Configuration.java:1355)
	at com.crowlogic.b2tf.Configuration.lambda$static$9(Configuration.java:1345)

**Comment by crowlogic** [comment]
I got it to work but I'm still having the issue with Lambda expression in statically initialized class, https://github.com/oracle/graal/issues/2135

**Comment by tpolecat** [comment]
@crowlogic could you share your solution to `java.lang.NoSuchMethodError: javax.xml.bind.annotation.XmlType.factoryClass` above? I am stuck at the same place.

**Comment by crowlogic** [comment]
@tpolecat I abandoned jaxb altogether and switched to another mechanism, com.fasterxml.jackson.dataformat.javaprop.JavaPropsMapper
