### ISSUE TITLE
GraalVM fails to build on Fedora 40 with gcc 14.1.1 due to unresolved issue in libffi 3.4.4

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#9123]
**Describe the issue**
GraalVM fails to build on Fedora 40 with gcc 14.1.1 due to an unresolved issue in libffi 3.4.4

**Steps to reproduce the issue**
1. clone reposiroty in a machine running Fedora 40 with gcc 14.1.1
2. `mx -v --primary-suite-path substratevm --components="Native Image" --native-image=native-image build`

**Describe GraalVM and your environment:**
 - GraalVM version: **9c0a7a4cfbb0b4690e004a9aa6484514defd3770**
 - JDK major version: **23**
 - OS: **Fedora 40**
 - Architecture: **AMD64**

**More details**

The build fails with:

```
echo MAKE libffi
MAKE libffi
make -C ../libffi-build > ../libffi.build.log
../libffi-3.4.4/src/tramp.c: In function ‘ffi_tramp_get_temp_file’:
../libffi-3.4.4/src/tramp.c:262:22: error: implicit declaration of function ‘open_temp_exec_file’ [-Wimplicit-function-declaration]
  262 |   tramp_globals.fd = open_temp_exec_file ();
      |                      ^~~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:1325: src/tramp.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:1397: all-recursive] Error 1
make[1]: *** [Makefile:625: all] Error 2
make: *** [Makefile:14: default] Error 2
[exit code: 2]
  File "/usr/lib64/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/zakkak/code/mx/src/mx/_impl/mx.py", line 393, in run
    super(_DummyProcess, self).run()
  File "/usr/lib64/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zakkak/code/mx/src/mx/_impl/mx.py", line 14646, in executeTask
    task.execute()
  File "/home/zakkak/code/mx/src/mx/_impl/build/tasks/build.py", line 165, in execute
    _built = self.build()
  File "/home/zakkak/code/graal-oracle/truffle/mx.truffle/mx_truffle.py", line 1652, in build
    self.delegate.build()
  File "/home/zakkak/code/mx/src/mx/_impl/mx.py", line 8029, in build
    run(cmdline, cwd=cwd, env=env)
  File "/home/zakkak/code/mx/src/mx/_impl/mx.py", line 13418, in run
    abort(retcode)
  File "/home/zakkak/code/mx/src/mx/_impl/support/logging.py", line 254, in abort
    traceback.print_stack()

Building libffi: Failed due to error: 2
[2024-06-17T08:56:32.958824447Z:127.0.0.1] [2024-06-17T08:56:32.958826161Z:127.0.0.1] Shutting downShutting down   
```

which is fixed by https://github.com/libffi/libffi/pull/764 in libffi 3.4.5+
