### ISSUE TITLE
native-image version 19.3.0-java11 fails with java.lang.Throwable in reflection config

### ISSUE THREAD

**Issue by jvasileff** [oracle/graal#1877]
The combination of 1) `java.lang.Throwable` in the reflection config and 2) a class that has a static field of type `java.util.logging.Logger` also in the reflection config causes `native-image` to fail with ``undefined reference to `JVM_FillInStackTrace'``

I distilled this down to compiling the class:

```java
public class Main {
    static java.util.logging.Logger log = null;
    public static void main(String[] args) { }
}
```
with the reflection config:
```
[
  { "name":"Main" },
  { "name":"java.lang.Throwable", "allDeclaredMethods":true }
]
```

Note that this compiles fine with the non-Java 11 `19.3.0` release.

The following is a reproduction using the official Docker image:

```
$ docker run --rm -i -t oracle/graalvm-ce:19.3.0-java11 /bin/bash
bash-4.2# gu install native-image
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Downloading: Component native-image: Native Image  from github.com
Installing new component: Native Image (org.graalvm.native-image, version 19.3.0)
Refreshed alternative links in /usr/bin/
bash-4.2# 
bash-4.2# echo '
> public class Main {
>     static java.util.logging.Logger log = null;
>     public static void main(String[] args) { }
> }
> ' > Main.java
bash-4.2# 
bash-4.2# echo '
> [
>   { "name":"Main" },
>   { "name":"java.lang.Throwable", "allDeclaredMethods":true }
> ]
> ' > reflect-config.json
bash-4.2# 
bash-4.2# javac Main.java
bash-4.2# 
bash-4.2# native-image Main -H:ReflectionConfigurationFiles=reflect-config.json
Build on Server(pid: 100, port: 43501)*
[main:100]    classlist:   2,559.23 ms
[main:100]        (cap):     678.55 ms
[main:100]        setup:   2,116.80 ms
[main:100]   (typeflow):   7,712.40 ms
[main:100]    (objects):   7,172.61 ms
[main:100]   (features):     325.55 ms
[main:100]     analysis:  15,529.25 ms
[main:100]     (clinit):     272.52 ms
[main:100]     universe:     741.40 ms
[main:100]      (parse):     945.30 ms
[main:100]     (inline):   1,417.27 ms
[main:100]    (compile):   8,157.27 ms
[main:100]      compile:  11,104.72 ms
[main:100]        image:     989.07 ms
[main:100]        write:     162.77 ms
Fatal error: java.lang.RuntimeException: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /main -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-14188168239209997184/exported_symbols.list -Wl,-x -L/tmp/SVM-14188168239209997184 -L/opt/graalvm-ce-java11-19.3.0/lib -L/opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64 /tmp/SVM-14188168239209997184/main.o /opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64/libffi.a /opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64/libjvm.a /opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64/libstrictmath.a /opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java11-19.3.0/lib/libnet.a /opt/graalvm-ce-java11-19.3.0/lib/libjava.a /opt/graalvm-ce-java11-19.3.0/lib/libzip.a /opt/graalvm-ce-java11-19.3.0/lib/libnio.a -lm -lpthread -lpthread -ldl -lz -lrt

Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39.0.1) (GCC) 
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' '/main' '-z' 'noexecstack' '-L/tmp/SVM-14188168239209997184' '-L/opt/graalvm-ce-java11-19.3.0/lib' '-L/opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/collect2 --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /main -z noexecstack /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbegin.o -L/tmp/SVM-14188168239209997184 -L/opt/graalvm-ce-java11-19.3.0/lib -L/opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../.. --gc-sections --dynamic-list /tmp/SVM-14188168239209997184/exported_symbols.list -x /tmp/SVM-14188168239209997184/main.o /opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64/libffi.a /opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64/libjvm.a /opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64/libstrictmath.a /opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java11-19.3.0/lib/libnet.a /opt/graalvm-ce-java11-19.3.0/lib/libjava.a /opt/graalvm-ce-java11-19.3.0/lib/libzip.a /opt/graalvm-ce-java11-19.3.0/lib/libnio.a -lm -lpthread -lpthread -ldl -lz -lrt -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crtn.o
/opt/graalvm-ce-java11-19.3.0/lib/libjava.a(Throwable.o): In function `Java_java_lang_Throwable_fillInStackTrace':
Throwable.c:(.text.Java_java_lang_Throwable_fillInStackTrace+0xd): undefined reference to `JVM_FillInStackTrace'
collect2: error: ld returned 1 exit status

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:315)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:454)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:402)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:339)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:420)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:336)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:280)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:240)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /main -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-14188168239209997184/exported_symbols.list -Wl,-x -L/tmp/SVM-14188168239209997184 -L/opt/graalvm-ce-java11-19.3.0/lib -L/opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64 /tmp/SVM-14188168239209997184/main.o /opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64/libffi.a /opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64/libjvm.a /opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64/libstrictmath.a /opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java11-19.3.0/lib/libnet.a /opt/graalvm-ce-java11-19.3.0/lib/libjava.a /opt/graalvm-ce-java11-19.3.0/lib/libzip.a /opt/graalvm-ce-java11-19.3.0/lib/libnio.a -lm -lpthread -lpthread -ldl -lz -lrt

Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39.0.1) (GCC) 
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' '/main' '-z' 'noexecstack' '-L/tmp/SVM-14188168239209997184' '-L/opt/graalvm-ce-java11-19.3.0/lib' '-L/opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/collect2 --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /main -z noexecstack /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbegin.o -L/tmp/SVM-14188168239209997184 -L/opt/graalvm-ce-java11-19.3.0/lib -L/opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../.. --gc-sections --dynamic-list /tmp/SVM-14188168239209997184/exported_symbols.list -x /tmp/SVM-14188168239209997184/main.o /opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64/libffi.a /opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64/libjvm.a /opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64/libstrictmath.a /opt/graalvm-ce-java11-19.3.0/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java11-19.3.0/lib/libnet.a /opt/graalvm-ce-java11-19.3.0/lib/libjava.a /opt/graalvm-ce-java11-19.3.0/lib/libzip.a /opt/graalvm-ce-java11-19.3.0/lib/libnio.a -lm -lpthread -lpthread -ldl -lz -lrt -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crtn.o
/opt/graalvm-ce-java11-19.3.0/lib/libjava.a(Throwable.o): In function `Java_java_lang_Throwable_fillInStackTrace':
Throwable.c:(.text.Java_java_lang_Throwable_fillInStackTrace+0xd): undefined reference to `JVM_FillInStackTrace'
collect2: error: ld returned 1 exit status

	at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:382)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:652)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
bash-4.2# 
```

**Comment by olpaw** [comment]
This is fixed on master and will also be in 19.3.1
