### ISSUE TITLE
graal master branch fails to build with OpenJDK 11.0.8 GA

### ISSUE THREAD

**Issue by jerboaa** [oracle/graal#2676]
**Describe the issue**
Trying to build graal master with OpenJDK 11.0.8 GA fails due to a JVM CI change[1] with:

```
[checking org.graalvm.compiler.replacements.classfile.ClassfileConstantPool]
/disk/graal/upstream-sources/graal/compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/classfile/ClassfileConstantPool.java:48: error: ClassfileConstantPool is not abstract and does not override abstract method lookupReferencedType(int,int) in ConstantPool
class ClassfileConstantPool implements ConstantPool {
^
```

**Steps to reproduce the issue**
1. Build OpenJDK 11u GA from source
```
$ hg clone http://hg.openjdk.java.net/jdk-updates/jdk11u
$ cd jdk11u
$ configure [...]
$ make graal-builder-image
```
2. Use the result `graal-builder-jdk` in `images` dir to build graal master which fails as above.

**More details**
Our fix for mandrel is being discussed here:
https://github.com/graalvm/mandrel/pull/76

[1] http://hg.openjdk.java.net/jdk-updates/jdk11u/rev/76890092b5ca

**Comment by jerboaa** [comment]
@adinn @thomaswue FYI. Happy to collaborate on an upstream fix.

**Comment by adinn** [comment]
@thomaswue @dougxc The openjdk update mentioned by @jerboaa is a necessary change to the JVMCI implementation that was duly backported to 11.0.8. Although we have a fix ready we don't want to step on your toes if you are also preparing one. Is there a graalvm repo patch in the pipeline for this that we will be able to pull into the mandrel repo? If not would the proposed Mandrel patch (graalvm#76)  be a suitable candidate for pushing to graalvm?

It looks like there may be other changes needed to allow 11.0.8 to be able to build GraalVM (the Mandrel thread identifies a problem building libgraal). Are there other upstream patches in progress that we might be able to pull down? Or should we investigate and provide patches which you might want to upstream?

**Comment by dougxc** [comment]
We have a PR for this that @tkrodriguez will push through asap.

**Comment by adinn** [comment]
Ok, great. Thanks for the prompt response!

**Comment by jerboaa** [comment]
FWIW, upstream binaries which allow one to reproduce this build failure are now available too:
https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/tag/jdk-11.0.8%2B10

**Comment by tkrodriguez** [comment]
https://github.com/oracle/graal/pull/2681 has the change against current master.  MethodCallTargetNode was refactored a bit recently so parts of it might need manual adjustment for 11.

**Comment by zakkak** [comment]
@jerboaa this should now be fixed. 
Note: Graal `master` still won't build with OpenJDK 11.0.8 GA, but this is due to https://github.com/oracle/graal/issues/2628

**Comment by jerboaa** [comment]
Yes, agreed. Closing.
