### ISSUE TITLE
[GR-43233] Native image fails to build with JDK 17.0.6+

### ISSUE THREAD

**Issue by galderz** [oracle/graal#5686]
Native image fails to build with the latest JDK 17 development branch. It throws:

```
java.lang.NoSuchMethodError: java.util.Base64$Decoder.decodeBlock([BII[BIZ)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.graphbuilderconf.InvocationPlugins$Checks.checkResolvable(InvocationPlugins.java:1056)
```

This is caused by [this JDK17 backport](https://github.com/openjdk/jdk17u-dev/commit/07050b000ce20350c55505fbc5595c0b6c3052b5). SVM assumes that if running below Java 18, there's no `isMIME` parameter. E.g.: 

```java
    public static final HotSpotForeignCallDescriptor BASE64_DECODE_BLOCK = JavaVersionUtil.JAVA_SPEC < 18
                    ? new HotSpotForeignCallDescriptor(LEAF, NOT_REEXECUTABLE, any(), "base64DecodeBlock", int.class, Word.class,
                                    int.class, int.class, Word.class, int.class, boolean.class)
                    : new HotSpotForeignCallDescriptor(LEAF, NOT_REEXECUTABLE, any(), "base64DecodeBlock", int.class, Word.class,
                                    int.class, int.class, Word.class, int.class, boolean.class, boolean.class);

```

However, once the backport was added, this check should no longer be necessary.

The backport is part of JDK 17.0.6+.

**Comment by galderz** [comment]
Can someone assign this to me?

**Comment by fniephaus** [comment]
@galderz could you please take a look at #5695?
