### ISSUE TITLE
Native-image throws `java.lang.NoClassDefFoundError: com/sun/net/httpserver/HttpHandler` with 22.2.r17, used to work in 21.3.0.r17

### ISSUE THREAD

**Issue by xonixx** [oracle/graal#4784]
**Describe the issue**
I'm using `com.sun.net.httpserver.HttpHandler` API to implement basic REST interface for my tool. Now, I'm able to compile jar with maven using GraalVM 22.2 CE for Java 17 (I'm installing it via Sdkman). But native-image step fails due to the problem in the title.

This used to work with 21.3.0.r17.

**Steps to reproduce the issue**
I have this problem in my project https://github.com/xonixx/serv. Just in case a build script is in  https://github.com/xonixx/serv/blob/master/Makesurefile.
Unfortunatelly I don't have specific steps to reproduce, since atm. I have some manual steps in the build process. But I can try to come up with more detailed instructions if need be.

**Describe GraalVM and your environment:**
```
$ cat /etc/issue ; uname -a
Linux Mint 20.3 Una \n \l

Linux xonix 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ java -version
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)
```

**More details**

```
Executing [
/home/xonix/.sdkman/candidates/java/22.2.r17-grl/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/com.sun.crypto.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.access.foreign=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.event=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.loader=org.graalvm.nativeimage.builder,org.graalvm.truffle \
--add-exports=java.base/jdk.internal.logger=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.misc=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/jdk.internal.module=jdk.internal.vm.compiler,org.graalvm.nativeimage.base,org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.org.objectweb.asm=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.perf=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.platform=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.ref=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/jdk.internal.reflect=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.vm.annotation=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.invoke.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.net=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.nio.ch=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/sun.reflect.annotation=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.factory=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.repository=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.scope=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.tree=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.jca=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.ssl=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.x509=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.text.spi=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.calendar=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.cldr=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.locale.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.locale=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.resources=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util=org.graalvm.nativeimage.builder \
--add-exports=java.desktop/sun.java2d.pipe=org.graalvm.nativeimage.builder \
--add-exports=java.desktop/sun.java2d=org.graalvm.nativeimage.builder \
--add-exports=java.management/com.sun.jmx.mbeanserver=org.graalvm.nativeimage.builder \
--add-exports=java.management/sun.management=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=java.xml.crypto/org.jcp.xml.dsig.internal.dom=org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.llvm \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.llvm,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.riscv64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.llvm,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.riscv64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.events=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.handlers=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal=org.graalvm.nativeimage.builder \
--add-exports=jdk.management/com.sun.management.internal=org.graalvm.nativeimage.builder \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx13329488280 \
-Djava.awt.headless=true \
-Dorg.graalvm.version=22.2.0 \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-javaagent:/home/xonix/.sdkman/candidates/java/22.2.r17-grl/lib/svm/builder/svm.jar \
--module-path \
/home/xonix/.sdkman/candidates/java/22.2.r17-grl/lib/truffle/truffle-api.jar:/home/xonix/.sdkman/candidates/java/22.2.r17-grl/lib/svm/builder/objectfile.jar:/home/xonix/.sdkman/candidates/java/22.2.r17-grl/lib/svm/builder/svm.jar:/home/xonix/.sdkman/candidates/java/22.2.r17-grl/lib/svm/builder/native-image-base.jar:/home/xonix/.sdkman/candidates/java/22.2.r17-grl/lib/svm/builder/llvm-wrapper-shadowed.jar:/home/xonix/.sdkman/candidates/java/22.2.r17-grl/lib/svm/builder/javacpp-platform-specific-shadowed.jar:/home/xonix/.sdkman/candidates/java/22.2.r17-grl/lib/svm/builder/pointsto.jar:/home/xonix/.sdkman/candidates/java/22.2.r17-grl/lib/svm/builder/javacpp-shadowed.jar:/home/xonix/.sdkman/candidates/java/22.2.r17-grl/lib/svm/builder/llvm-platform-specific-shadowed.jar:/home/xonix/.sdkman/candidates/java/22.2.r17-grl/lib/svm/builder/svm-llvm.jar \
--module \
org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner \
-watchpid \
490815 \
-imagecp \
/home/xonix/proj/serv/target/classes:/home/xonix/.m2/repository/commons-cli/commons-cli/1.5.0/commons-cli-1.5.0.jar:/home/xonix/.m2/repository/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar:/home/xonix/.m2/repository/com/github/xonixx/java-utils/v0.9.1/java-utils-v0.9.1.jar \
-imagemp \
/home/xonix/.sdkman/candidates/java/22.2.r17-grl/lib/svm/library-support.jar \
-H:CLibraryPath=/home/xonix/.sdkman/candidates/java/22.2.r17-grl/lib/svm/clibraries/linux-amd64 \
-H:Path=/home/xonix/proj/serv/build \
'-H:IncludeResources=.*ico$' \
-H:Log=registerResource: \
-H:+DumpTargetInfo \
'-H:Class@explicit main-class=com.cmlteam.serv.Serv' \
'-H:Name@main-class lower case as image name=com.cmlteam.serv.serv'
]
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
========================================================================================================================
GraalVM Native Image: Generating 'com.cmlteam.serv.serv' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (0.0s @ 0.15GB)
Fatal error: java.lang.NoClassDefFoundError: com/sun/net/httpserver/HttpHandler
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2673)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:359)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Caused by: java.lang.ClassNotFoundException: com.sun.net.httpserver.HttpHandler
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 6 more
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1716)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1413)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1374)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1361)
```

**Comment by fniephaus** [comment]
Since the [22.2 release](https://www.graalvm.org/release-notes/22_2/), GraalVM Native Image runs on the module path to separate it clearly from user applications. When it was running on the class path, some default modules were added automatically. Your application still uses the class path, so what you need to do on 22.2 is to add `--add-modules jdk.httpserver` explicitly to your `/bin/native-image` invocation. In the next release, this should no longer be necessary because Native Image will follow the `/bin/java` behavior: when the class path is used, a set of default modules will be added automatically (so you should be able to remove `--add-modules jdk.httpserver` in future).

**Comment by xonixx** [comment]
Thank you, this helped.
