### ISSUE TITLE
[native-image] Reflection config with java.nio.file.Files does not work with JDK 11 on macOS 10.14.6

### ISSUE THREAD

**Issue by borkdude** [oracle/graal#2015]
**Problem statement**

Compilation works fine on JDK8 for one of my projects, but not on JDK11 with macOS 10.14.6. This is the output produced on JDK11:

https://gist.github.com/borkdude/bc0d9941a9432d41a25665fc1ce9c760

Excerpt:

```
Undefined symbols for architecture x86_64:
  "_UTTypeCopyPreferredTagWithClass", referenced from:
      _Java_sun_nio_fs_UTIFileTypeDetector_probe0 in libnio.a(UTIFileTypeDetector.o)
  "_UTTypeCreatePreferredIdentifierForTag", referenced from:
      _Java_sun_nio_fs_UTIFileTypeDetector_probe0 in libnio.a(UTIFileTypeDetector.o)
  "_kUTTagClassFilenameExtension", referenced from:
      _Java_sun_nio_fs_UTIFileTypeDetector_probe0 in libnio.a(UTIFileTypeDetector.o)
  "_kUTTagClassMIMEType", referenced from:
      _Java_sun_nio_fs_UTIFileTypeDetector_probe0 in libnio.a(UTIFileTypeDetector.o)
ld: symbol(s) not found for architecture x86_64
```

**Reproduction**

Jar file: see attachment. Unzip first.
[babashka-0.0.46-standalone.jar.zip](https://github.com/oracle/graal/files/3991581/babashka-0.0.46-standalone.jar.zip)

Contents of `reflection.json`:

```
[ {
  "name" : "java.nio.file.Files",
  "allPublicMethods" : true,
  "allPublicFields" : true,
  "allPublicConstructors" : true
} ]
```

Compilation script:

```
#!/usr/bin/env bash

$NATIVE_IMAGE \
  -jar babashka-0.0.46-standalone.jar \
  -H:Name=bb \
  -H:+ReportExceptionStackTraces \
  -J-Dclojure.spec.skip-macros=true \
  -J-Dclojure.compiler.direct-linking=true \
  "-H:IncludeResources=BABASHKA_VERSION" \
  "-H:IncludeResources=SCI_VERSION" \
  -H:ReflectionConfigurationFiles=reflection.json \
  --initialize-at-run-time=java.lang.Math\$RandomNumberGeneratorHolder \
  --initialize-at-build-time \
  -H:Log=registerResource: \
  -H:EnableURLProtocols=http,https \
  --enable-all-security-services \
  -H:+JNI \
  --verbose \
  --no-fallback \
  --no-server \
  "-J-Xmx3g"
```

Note: set `NATIVE_IMAGE` to a `java11` version of GraalVM:
```
 export NATIVE_IMAGE=/Users/borkdude/Downloads/graalvm-ce-java11-19.3.0/Contents/Home/bin/native-image
```

**Comment by borkdude** [comment]
Might be related to #1946?

**Comment by eginez** [comment]
fixed by https://github.com/oracle/graal/commit/f3592212e82d0f2efc4acc87d3d7b8412cd093b6. 

and @borkdude great work on babashka I really enjoy the possibilities on having a clojure repl natively

**Comment by borkdude** [comment]
@eginez Thank you for both this commit and the compliment. 

Any ideas in which future versions of GraalVM this will be available? Any progress on making nightlies available?

**Comment by borkdude** [comment]
Confirming that this issue if fixed with compiling with https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/20.1.0-dev-20200208_0320.
