### ISSUE TITLE
[dsl] Overriding library messages can cause compilation errors (regression)

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#3078]
**Have you verified this issue still happens when using the latest snapshot?**
Yes, still happening on [current master](https://github.com/oracle/graal/commit/5967b4ee9d81a74322a2b69412cfa298fc5caf4d) and used to work fine in `20.3.0`.

**Code snippet or code repository that reproduces the issue**
```java
package de.hpi.swa.trufflesqueak.model;

import com.oracle.truffle.api.dsl.Fallback;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.interop.InteropLibrary;
import com.oracle.truffle.api.interop.TruffleObject;
import com.oracle.truffle.api.interop.UnsupportedMessageException;
import com.oracle.truffle.api.library.ExportLibrary;
import com.oracle.truffle.api.library.ExportMessage;
import com.oracle.truffle.api.utilities.TriState;

@ExportLibrary(InteropLibrary.class)
public class MyObject implements TruffleObject {

    @ExportMessage
    protected static final class IsIdenticalOrUndefined {
        @Specialization
        protected static TriState doMyObject(final MyObject receiver, final MyObject other) {
            return TriState.valueOf(receiver == other);
        }

        @Fallback
        @SuppressWarnings("unused")
        protected static TriState doOther(final MyObject receiver, final Object other) {
            return TriState.UNDEFINED;
        }
    }

    @ExportMessage
    protected final int identityHashCode() throws UnsupportedMessageException {
        return 0;
    }

    @ExportLibrary(InteropLibrary.class)
    public static class MySubObject extends MyObject {

        @ExportMessage
        protected static TriState isIdenticalOrUndefined(final MySubObject receiver, final Object other) {
            return TriState.TRUE;
        }
    }
}
```

**Error**
```
Compiling de.hpi.swa.trufflesqueak with javac-daemon(JDK 11)... [trufflesqueak/mxbuild/src/de.hpi.swa.trufflesqueak/bin/de/hpi/swa/trufflesqueak/SqueakOptions.class does not exist]
trufflesqueak/mxbuild/src/de.hpi.swa.trufflesqueak/src_gen/de/hpi/swa/trufflesqueak/model/MySubObjectGen.java:75: error: isIdenticalOrUndefined(Object,Object) in de.hpi.swa.trufflesqueak.model.MySubObjectGen.InteropLibraryExports.Uncached cannot override isIdenticalOrUndefined(Object,Object) in de.hpi.swa.trufflesqueak.model.MyObjectGen.InteropLibraryExports.Uncached
            protected TriState isIdenticalOrUndefined(Object receiver, Object other) {
                               ^
  attempting to assign weaker access privileges; was public
1 error
```

Please assign to @chumer.
