### ISSUE TITLE
 java.lang.NoClassDefFoundError: jdk/internal/misc/JavaBeansAccess

### ISSUE THREAD

**Issue by ltlgobearssf** [oracle/graal#2311]
graalvm  version graalvm-ee-java11-20.0.0 cannot be used with jdk.internal.misc.JavaBeansAccess class, even  with --add-exports options.  Same code that works in openjdk 11.0.6 and graalvm ce, fails in graalvm ee version graalvm-ee-java11-20.0.0

Repro:
```
// Test program JBA.java
import jdk.internal.misc.JavaBeansAccess;
import jdk.internal.misc.SharedSecrets;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
class JBA {
    public static void main(String [] args) {
         SharedSecrets.setJavaBeansAccess(new JavaBeansAccess() {
            @Override
            public Method getReadMethod(Class<?> clazz, String property) throws Exception {
                return null;
            }
            @Override
            public String[] getConstructorPropertiesValue(Constructor<?> ctr) {
                return null;
            }
        });
    }
}
// -- End test program

```
This can be compiled like this, works both in graalvm and jdk 11.0.6:
**javac --add-exports java.base/jdk.internal.misc=ALL-UNNAMED JBA.java**

It can be run with this command:
**java --add-exports java.base/jdk.internal.misc=ALL-UNNAMED JBA**

Running it works in java 11.0.6 but **FAILS** in graalvm(version graalvm-ee-java11-20.0.0) with:
**Error: Unable to initialize main class JBA
Caused by: java.lang.NoClassDefFoundError: jdk/internal/misc/JavaBeansAccess**

**Comment by dougxc** [comment]
That's because GraalVM on JDK 11 includes a backport of https://bugs.openjdk.java.net/browse/JDK-8211122.

**Comment by ltlgobearssf** [comment]
Got it, thanks for the quick feedback
